// <auto-generated />
using System;
using Filmoteka.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filmoteka.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702200438_AddEmailAndUserSupport")]
    partial class AddEmailAndUserSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmReziser", b =>
                {
                    b.Property<Guid>("FilmoviId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReziseriId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FilmoviId", "ReziseriId");

                    b.HasIndex("ReziseriId");

                    b.ToTable("FilmReziser", (string)null);
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Film", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DostupnoUBioskopu")
                        .HasColumnType("bit")
                        .HasColumnName("DostupnoUBioskopu");

                    b.Property<int>("Godina")
                        .HasColumnType("int")
                        .HasColumnName("GodinaFilma");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NazivFilma");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("OpisFilma");

                    b.Property<Guid>("ZanrId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ZanrId");

                    b.HasKey("Id");

                    b.HasIndex("ZanrId");

                    b.ToTable("Filmovi");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Korisnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(83)
                        .HasColumnType("nvarchar(83)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Projekcija", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DostupnaMesta")
                        .HasColumnType("int")
                        .HasColumnName("DostupnaMesta");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FilmId");

                    b.Property<Guid>("SalaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SalaId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<DateTime>("VremePocetka")
                        .HasColumnType("datetime2")
                        .HasColumnName("VremePocetka");

                    b.Property<DateTime>("VremeZavrsetka")
                        .HasColumnType("datetime2")
                        .HasColumnName("VremeZavrsetka");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("SalaId");

                    b.ToTable("Projekcije");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Rezervacija", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumRezervacije")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatumRezervacije");

                    b.Property<string>("KorisnikEmail")
                        .IsRequired()
                        .HasMaxLength(83)
                        .HasColumnType("nvarchar(83)")
                        .HasColumnName("KorisnikEmail");

                    b.Property<string>("KorisnikIme")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)")
                        .HasColumnName("KorisnikIme");

                    b.Property<bool>("PodsetnikPoslat")
                        .HasColumnType("bit")
                        .HasColumnName("PodsetnikPoslat");

                    b.Property<Guid>("ProjekcijaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProjekcijaId");

                    b.HasKey("Id");

                    b.HasIndex("ProjekcijaId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Reziser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatumRodjenja");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ImeRezisera");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PrezimeRezisera");

                    b.HasKey("Id");

                    b.ToTable("Reziseri");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Sala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("KapacitetSale");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NazivSale");

                    b.Property<int>("Tip")
                        .HasColumnType("int")
                        .HasColumnName("TipSale");

                    b.HasKey("Id");

                    b.HasIndex("Naziv")
                        .IsUnique();

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Zanr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NazivZanra");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");
                });

            modelBuilder.Entity("FilmReziser", b =>
                {
                    b.HasOne("Filmoteka.Server.Models.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmoviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Filmoteka.Server.Models.Reziser", null)
                        .WithMany()
                        .HasForeignKey("ReziseriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Film", b =>
                {
                    b.HasOne("Filmoteka.Server.Models.Zanr", "Zanr")
                        .WithMany("Filmovi")
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Projekcija", b =>
                {
                    b.HasOne("Filmoteka.Server.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Filmoteka.Server.Models.Sala", "Sala")
                        .WithMany("Projekcije")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Rezervacija", b =>
                {
                    b.HasOne("Filmoteka.Server.Models.Projekcija", "Projekcija")
                        .WithMany("Rezervacije")
                        .HasForeignKey("ProjekcijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekcija");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Projekcija", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Sala", b =>
                {
                    b.Navigation("Projekcije");
                });

            modelBuilder.Entity("Filmoteka.Server.Models.Zanr", b =>
                {
                    b.Navigation("Filmovi");
                });
#pragma warning restore 612, 618
        }
    }
}
